from typing import Any, Callable, Dict, List

from apps.rtagent.backend.src.agents.artagent.tool_store.emergency import escalate_emergency
from apps.rtagent.backend.src.agents.artagent.tool_store.handoffs import (
    escalate_human,
)

# Retail Tools
from apps.rtagent.backend.src.agents.artagent.tool_store.retail_product_tools import (
    search_products_general,
    search_products_filtered,
    check_product_availability,
    search_complementary_items,
    get_outfit_suggestions,
    get_customer_style_profile,
    get_customer_measurements,
    get_product_images,
    get_style_inspiration,
    suggest_color_combinations,
)
from apps.rtagent.backend.src.agents.artagent.tool_store.retail_handoffs import (
    handoff_to_stylist,
    handoff_to_postsale,
    handoff_to_concierge,
    stylist_handoff_to_postsale,
    escalate_to_human as retail_escalate_to_human,
)
from apps.rtagent.backend.src.agents.artagent.tool_store.retail_checkout_tools import (
    initiate_checkout,
    apply_membership_discount,
    get_shipping_options,
    process_payment,
    create_order,
    get_order_status,
    apply_promo_code,
    save_payment_method,
    get_order_history,
    cancel_order,
    modify_order,
    initiate_return,
    initiate_exchange,
    check_return_eligibility,
    process_refund,
    select_shipping_method,
    track_shipment,
    update_shipping_address,
    get_customer_profile,
    update_payment_method,
    get_loyalty_balance,
    apply_loyalty_points,
    check_gift_card_balance,
    apply_gift_card,
    send_order_confirmation_email,
    send_return_label_email,
    escalate_payment_issue,
    escalate_shipping_issue,
)
from apps.rtagent.backend.src.agents.artagent.tool_store.retail_store_info_tools import (
    get_product_details,
    get_pricing_for_tier,
    check_current_promotions,
    get_store_hours,
    get_return_policy,
    get_shipping_policy,
    get_warranty_info,
)
from apps.rtagent.backend.src.agents.artagent.tool_store.postsale_tools import (
    get_customer_info,
    get_product_price,
    send_order_confirmation_email as postsale_send_email,  # Different implementation
)

from apps.rtagent.backend.src.agents.artagent.tool_store.financial_mfa_auth import (
    verify_client_identity,
    verify_fraud_client_identity,
    send_mfa_code,
    verify_mfa_code,
    check_transaction_authorization,
    resend_mfa_code,
)
from apps.rtagent.backend.src.agents.artagent.tool_store.fraud_detection import (
    analyze_recent_transactions,
    check_suspicious_activity,
    create_fraud_case,
    block_card_emergency,
    provide_fraud_education,
    ship_replacement_card,
    send_fraud_case_email,
    create_transaction_dispute,
)
from apps.rtagent.backend.src.agents.artagent.tool_store.transfer_agency_tools import (
    get_client_data,
    get_drip_positions,
    check_compliance_status,
    calculate_liquidation_proceeds,
)
from utils.ml_logging import get_logger

log = get_logger("tools_helper")

from apps.rtagent.backend.src.agents.artagent.tool_store.schemas import (
    escalate_emergency_schema,
    escalate_human_schema,
    verify_client_identity_schema,
    verify_fraud_client_identity_schema,
    send_mfa_code_schema,
    verify_mfa_code_schema,
    resend_mfa_code_schema,
    check_transaction_authorization_schema,
    analyze_recent_transactions_schema,
    check_suspicious_activity_schema,
    create_fraud_case_schema,
    block_card_emergency_schema,
    provide_fraud_education_schema,
    ship_replacement_card_schema,
    send_fraud_case_email_schema,
    create_transaction_dispute_schema,
    # Transfer Agency Tools
    get_client_data_schema,
    get_drip_positions_schema,
    check_compliance_status_schema,
    calculate_liquidation_proceeds_schema,
)

# Retail Tool Schemas
from apps.rtagent.backend.src.agents.artagent.tool_store.retail_schemas import (
    search_products_general_schema,
    search_products_filtered_schema,
    check_product_availability_schema,
    search_complementary_items_schema,
    get_outfit_suggestions_schema,
    get_customer_style_profile_schema,
    get_customer_measurements_schema,
    get_product_images_schema,
    get_style_inspiration_schema,
    suggest_color_combinations_schema,
    handoff_to_stylist_schema,
    handoff_to_postsale_schema,
    stylist_handoff_to_postsale_schema,
    handoff_to_concierge_schema,
    escalate_to_human_schema as retail_escalate_to_human_schema,
    initiate_checkout_schema,
    apply_membership_discount_schema,
    apply_promo_code_schema,
    save_payment_method_schema,
    get_shipping_options_schema,
    process_payment_schema,
    create_order_schema,
    get_order_status_schema,
    get_order_history_schema,
    cancel_order_schema,
    modify_order_schema,
    initiate_return_schema,
    initiate_exchange_schema,
    check_return_eligibility_schema,
    process_refund_schema,
    select_shipping_method_schema,
    track_shipment_schema,
    update_shipping_address_schema,
    get_customer_profile_schema,
    update_payment_method_schema,
    get_loyalty_balance_schema,
    apply_loyalty_points_schema,
    check_gift_card_balance_schema,
    apply_gift_card_schema,
    get_product_details_schema,
    get_pricing_for_tier_schema,
    check_current_promotions_schema,
    get_store_hours_schema,
    get_return_policy_schema,
    get_shipping_policy_schema,
    get_warranty_info_schema,
    send_order_confirmation_email_schema,
    send_return_label_email_schema,
    escalate_payment_issue_schema,
    escalate_shipping_issue_schema,
)
from apps.rtagent.backend.src.agents.artagent.tool_store.postsale_schemas import (
    get_customer_info_schema,
    get_product_price_schema,
)

function_mapping: Dict[str, Callable[..., Any]] = {
    "escalate_emergency": escalate_emergency,
    "escalate_human": escalate_human,
    "verify_client_identity": verify_client_identity,
    "verify_fraud_client_identity": verify_fraud_client_identity,
    "send_mfa_code": send_mfa_code,
    "verify_mfa_code": verify_mfa_code,
    "check_transaction_authorization": check_transaction_authorization,
    "resend_mfa_code": resend_mfa_code,
    # Fraud Detection Tools
    "analyze_recent_transactions": analyze_recent_transactions,
    "check_suspicious_activity": check_suspicious_activity,
    "create_fraud_case": create_fraud_case,
    "block_card_emergency": block_card_emergency,
    "provide_fraud_education": provide_fraud_education,
    "ship_replacement_card": ship_replacement_card,
    "send_fraud_case_email": send_fraud_case_email,
    "create_transaction_dispute": create_transaction_dispute,
    # Transfer Agency Tools
    "get_client_data": get_client_data,
    "get_drip_positions": get_drip_positions,
    "check_compliance_status": check_compliance_status,
    "calculate_liquidation_proceeds": calculate_liquidation_proceeds,
    # Retail Product Search Tools
    "search_products_general": search_products_general,
    "search_products_filtered": search_products_filtered,
    "check_product_availability": check_product_availability,
    "search_complementary_items": search_complementary_items,
    "get_outfit_suggestions": get_outfit_suggestions,
    "get_customer_style_profile": get_customer_style_profile,
    "get_customer_measurements": get_customer_measurements,
    "get_product_images": get_product_images,
    "get_style_inspiration": get_style_inspiration,
    "suggest_color_combinations": suggest_color_combinations,
    # Retail Handoff Tools
    "handoff_to_stylist": handoff_to_stylist,
    "handoff_to_postsale": handoff_to_postsale,
    "stylist_handoff_to_postsale": stylist_handoff_to_postsale,
    "handoff_to_concierge": handoff_to_concierge,
    "escalate_to_human": retail_escalate_to_human,
    # Retail Checkout Tools
    "initiate_checkout": initiate_checkout,
    "apply_membership_discount": apply_membership_discount,
    "apply_promo_code": apply_promo_code,
    "save_payment_method": save_payment_method,
    "get_shipping_options": get_shipping_options,
    "process_payment": process_payment,
    "create_order": create_order,
    "get_order_status": get_order_status,
    "get_order_history": get_order_history,
    "cancel_order": cancel_order,
    "modify_order": modify_order,
    # Retail Returns & Exchanges
    "initiate_return": initiate_return,
    "initiate_exchange": initiate_exchange,
    "check_return_eligibility": check_return_eligibility,
    "process_refund": process_refund,
    # Retail Shipping Tools
    "select_shipping_method": select_shipping_method,
    "track_shipment": track_shipment,
    "update_shipping_address": update_shipping_address,
    # Retail Customer Account Tools
    "get_customer_profile": get_customer_profile,
    "update_payment_method": update_payment_method,
    "get_loyalty_balance": get_loyalty_balance,
    "apply_loyalty_points": apply_loyalty_points,
    "check_gift_card_balance": check_gift_card_balance,
    "apply_gift_card": apply_gift_card,
    # Retail Store Info Tools
    "get_product_details": get_product_details,
    "get_pricing_for_tier": get_pricing_for_tier,
    "check_current_promotions": check_current_promotions,
    "get_store_hours": get_store_hours,
    "get_return_policy": get_return_policy,
    "get_shipping_policy": get_shipping_policy,
    "get_warranty_info": get_warranty_info,
    "send_order_confirmation_email": send_order_confirmation_email,
    "send_return_label_email": send_return_label_email,
    # Post-Sale Checkout Tools (New Simplified Implementation)
    "get_customer_info": get_customer_info,
    "get_product_price": get_product_price,
    # Retail Escalation Tools
    "escalate_payment_issue": escalate_payment_issue,
    "escalate_shipping_issue": escalate_shipping_issue,
}


available_tools: List[Dict[str, Any]] = [
    {"type": "function", "function": escalate_emergency_schema},
    {"type": "function", "function": escalate_human_schema},
    {"type": "function", "function": verify_client_identity_schema},
    {"type": "function", "function": verify_fraud_client_identity_schema},
    {"type": "function", "function": send_mfa_code_schema},
    {"type": "function", "function": verify_mfa_code_schema},
    {"type": "function", "function": check_transaction_authorization_schema},
    {"type": "function", "function": resend_mfa_code_schema},
    # Fraud Detection Tools
    {"type": "function", "function": analyze_recent_transactions_schema},
    {"type": "function", "function": check_suspicious_activity_schema},
    {"type": "function", "function": create_fraud_case_schema},
    {"type": "function", "function": block_card_emergency_schema},
    {"type": "function", "function": provide_fraud_education_schema},
    {"type": "function", "function": ship_replacement_card_schema},
    {"type": "function", "function": send_fraud_case_email_schema},
    {"type": "function", "function": create_transaction_dispute_schema},
    # Transfer Agency Tools
    {"type": "function", "function": get_client_data_schema},
    {"type": "function", "function": get_drip_positions_schema},
    {"type": "function", "function": check_compliance_status_schema},
    {"type": "function", "function": calculate_liquidation_proceeds_schema},
    # Retail Product Search Tools
    {"type": "function", "function": search_products_general_schema},
    {"type": "function", "function": search_products_filtered_schema},
    {"type": "function", "function": check_product_availability_schema},
    {"type": "function", "function": search_complementary_items_schema},
    {"type": "function", "function": get_outfit_suggestions_schema},
    {"type": "function", "function": get_customer_style_profile_schema},
    {"type": "function", "function": get_customer_measurements_schema},
    {"type": "function", "function": get_product_images_schema},
    {"type": "function", "function": get_style_inspiration_schema},
    {"type": "function", "function": suggest_color_combinations_schema},
    # Retail Handoff Tools
    {"type": "function", "function": handoff_to_stylist_schema},
    {"type": "function", "function": handoff_to_postsale_schema},
    {"type": "function", "function": stylist_handoff_to_postsale_schema},
    {"type": "function", "function": handoff_to_concierge_schema},
    {"type": "function", "function": retail_escalate_to_human_schema},
    # Retail Checkout Tools
    {"type": "function", "function": initiate_checkout_schema},
    {"type": "function", "function": apply_membership_discount_schema},
    {"type": "function", "function": apply_promo_code_schema},
    {"type": "function", "function": save_payment_method_schema},
    {"type": "function", "function": get_shipping_options_schema},
    {"type": "function", "function": process_payment_schema},
    {"type": "function", "function": create_order_schema},
    {"type": "function", "function": get_order_status_schema},
    {"type": "function", "function": get_order_history_schema},
    {"type": "function", "function": cancel_order_schema},
    {"type": "function", "function": modify_order_schema},
    # Retail Returns & Exchanges
    {"type": "function", "function": initiate_return_schema},
    {"type": "function", "function": initiate_exchange_schema},
    {"type": "function", "function": check_return_eligibility_schema},
    {"type": "function", "function": process_refund_schema},
    # Retail Shipping Tools
    {"type": "function", "function": select_shipping_method_schema},
    {"type": "function", "function": track_shipment_schema},
    {"type": "function", "function": update_shipping_address_schema},
    # Retail Customer Account Tools
    {"type": "function", "function": get_customer_profile_schema},
    {"type": "function", "function": update_payment_method_schema},
    {"type": "function", "function": get_loyalty_balance_schema},
    {"type": "function", "function": apply_loyalty_points_schema},
    {"type": "function", "function": check_gift_card_balance_schema},
    {"type": "function", "function": apply_gift_card_schema},
    # Retail Store Info Tools
    {"type": "function", "function": get_product_details_schema},
    {"type": "function", "function": get_pricing_for_tier_schema},
    {"type": "function", "function": check_current_promotions_schema},
    {"type": "function", "function": get_store_hours_schema},
    {"type": "function", "function": get_return_policy_schema},
    {"type": "function", "function": get_shipping_policy_schema},
    {"type": "function", "function": get_warranty_info_schema},
    {"type": "function", "function": send_order_confirmation_email_schema},
    {"type": "function", "function": send_return_label_email_schema},
    # Retail Escalation Tools
    {"type": "function", "function": escalate_payment_issue_schema},
    {"type": "function", "function": escalate_shipping_issue_schema},
    # Post-Sale Checkout Tools (Simplified Implementation)
    {"type": "function", "function": get_customer_info_schema},
    {"type": "function", "function": get_product_price_schema},
]

TOOL_REGISTRY: dict[str, dict] = {t["function"]["name"]: t for t in available_tools}
