"""
Connection and Session Management Configuration (DEPRECATED)
============================================================

This file is deprecated. Import from config or config.settings instead.
"""

from .settings import (
    MAX_WEBSOCKET_CONNECTIONS,
    CONNECTION_QUEUE_SIZE,
    ENABLE_CONNECTION_LIMITS,
    CONNECTION_WARNING_THRESHOLD,
    CONNECTION_CRITICAL_THRESHOLD,
    CONNECTION_TIMEOUT_SECONDS,
    HEARTBEAT_INTERVAL_SECONDS,
    SESSION_TTL_SECONDS,
    SESSION_CLEANUP_INTERVAL,
    MAX_CONCURRENT_SESSIONS,
    ENABLE_SESSION_PERSISTENCE,
    SESSION_STATE_TTL,
    POOL_SIZE_TTS,
    POOL_SIZE_STT,
    POOL_LOW_WATER_MARK,
    POOL_HIGH_WATER_MARK,
    POOL_ACQUIRE_TIMEOUT,
)
